spring:
  application:
    name: aop_with_caching

#  data base config :
  datasource:
    url: jdbc:mysql://localhost:3306/aopandcaching
    username: root
    password: ajstyles
    driver-class-name: com.mysql.cj.jdbc.Driver

#  hibernate & jpa
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
